### ISSUE TITLE
Edit landing page 

### ISSUE THREAD

**Issue by IlariaStirpe** [Poseidon-DAO/poseidondao.org#65]
[POSEIDON DAO LANDING PAGE.docx](https://github.com/Poseidon-DAO/poseidondao.org/files/10074693/POSEIDON.DAO.LANDING.PAGE.docx)

**Comment by xn3cr0nx** [comment]
pasting here for clarity:


![Image](https://user-images.githubusercontent.com/18316027/205258852-58ebc34e-8735-4214-9628-cfe5abe2d0db.png)
